; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = normal_main

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32dev
framework = arduino
monitor_speed = 115200
build_unflags = 
	-std=gnu++11
build_flags = 
	-std=gnu++2a
	-Wall

[env:normal_main]
extends = env
lib_deps =
	https://github.com/rodneybakiskan/ps5-esp32
build_src_filter =
	+<normal_main.cpp>
	-<dm_test_main.cpp>
	-<dm_id_writer_main.cpp>

[env:dmtest]
extends = env
build_src_filter =
	-<normal_main.cpp>
	+<dm_test_main.cpp>
	-<dm_id_writer_main.cpp>

[env:dmidwriter]
extends = env
build_src_filter =
	-<normal_main.cpp>
	-<dm_test_main.cpp>
	+<dm_id_writer_main.cpp>
